// Constraint-driven episode generator (Phase 3).
//
// Replaces the 3500-line oracle-based episode.cpp with a ConstraintState x
// MotifOp driven generator. Episodes are generated by:
//   1. Selecting motifs from the pool by character
//   2. Applying MotifOp transformations
//   3. Planning Fortspinnung phases (Kernel->Sequence->Dissolution)
//   4. Evaluating each candidate via ConstraintState.evaluate()
//   5. Advancing state via ConstraintState.advance()

#ifndef BACH_CONSTRAINT_EPISODE_GENERATOR_H
#define BACH_CONSTRAINT_EPISODE_GENERATOR_H

#include "constraint/motif_constraint.h"

namespace bach {

/// @brief Generate an episode using the constraint-driven pipeline.
///
/// Algorithm:
///   1. Get CharacterEpisodeParams for the subject character
///   2. Select motif from pool (getForOp with character's voice0_initial)
///   3. Apply voice0/voice1 transformations via applyMotifOp()
///   4. Plan Fortspinnung arc via planFortspinnung()
///   5. For each step, generate candidates and evaluate via ConstraintState
///   6. Place the highest-scoring candidate
///   7. Check is_dead() for deadlock -> success=false
///   8. Apply invertible counterpoint for odd episode_index (num_voices>=2)
///
/// @param request Episode generation parameters.
/// @return Episode result with notes and exit state.
EpisodeResult generateConstraintEpisode(const EpisodeRequest& request);

}  // namespace bach

#endif  // BACH_CONSTRAINT_EPISODE_GENERATOR_H
